GSM-MSG/SMS-Android

presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt, presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginScreen.kt, presentation/src/main/java/com/sms/presentation/main/ui/login/component/TopComponent.kt, presentation/src/main/res/values/strings.xml
- 로그인 페이지 디자인 변경사항을 적용합니다.
- 로그인 페이지 상단 컴포넌트의 텍스트를 전부 대문자로 변경했습니다.
=> 🔀 :: (#35) - 로그인 페이지 디자인 변경사항 적용

design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
텍스트 필드 컴포넌트를 생성합니다.
옆에 아이콘 색 관련 이슈는 @khs3994 
https://github.com/GSM-MSG/SMS-Android/assets/82383983/53e90581-af44-4564-93af-1ee5bd2c4fda
=> 🔀 :: (#45) - create text field of design component

presentation/src/main/java/com/sms/presentation/main/ui/main/component/MainScreenTopBar.kt, presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
- 메인리스트 페이지에서 학생 수 뜨도록 처리
- 메인 리스트 맨 위 아이템에 학생 수가 뜨는 UI추가
- 스크롤 된 상태면 탑바 밑에 디바이더가 뜨도록 처리
=> 🔀 :: (#134) - 메인리스트 페이지에서 학생 수 뜨도록 처리

design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt, design-system/src/main/res/drawable/ic_red_logout.xml, design-system/src/main/res/drawable/ic_red_withdrawal.xml, presentation/src/main/java/com/sms/presentation/main/ui/main/component/ModalBottomSheetItem.kt, presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
- 로그아웃, 회원탈퇴를 위한 바텀시트 UI제작
https://github.com/GSM-MSG/SMS-Android/assets/80810303/485687f3-927d-41be-9267-760c4a4e9492
10303/f01b68f9-8b71-4960-92a9-71c070828e28">
- modal 바텀시트를 활용하여 제작
- 중복되는 코드 컴포넌트로 분리
- 다른 다이얼로그 들과도 겹치는 코드가 있어서 추후에 디자인 시스템에 공용 다이얼로그 아이템 추가 필요
=> 🔀 :: (#140) - 로그아웃, 회원탈퇴를 위한 바텀시트 UI제작

presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
- 게스트 상태일때 디테일 페이지의 이름이 소금으로 치환되지 않는 이슈를 해결합니다.
- 게스트상태일때 정보를 넘겨줄때 
```kotlin
replace("**","소금")
```
하도록 처리
=> 🔀 :: (#168) - 게스트 상태일때 디테일 페이지 이슈 해결

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/util/hideKeyboard.kt
키보드가 떠있는 상태에서 바텀 시트를 띄우면 바텀 시트가 보이지 않는 문제를 키보드를 hide시켜 해결하였습니다.
=> 🔀 :: (#198) - close softkeyboard when showing bottom sheet

design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
- SmsCustomTextFiled Leading Icon 이슈 해결
- icon이 전달 되지 않은 경우에 OutlinedTextField의 Leading Icon에 null이 전달되도록 코드 수정
=> 🔀 :: (#224) - SmsCustomTextFiled Leading Icon 이슈 해결

buildSrc/src/main/java/Versions.kt, presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt, presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginScreen.kt
- GAuth v1.1.2 적용
- GAuth Version Up을 진행했습니다.
- 뒤로가기 클릭시에 다시 인트로 페이지로 나와지도록 코드 추가
- 자연스러운 뷰 전환을 위해 애니메이션 추가
https://github.com/GSM-MSG/SMS-Android/assets/80810303/d7974276-d512-433f-9aa8-110e480d7d2a
- GAuthWebView에 대한 컴포넌트가 LoginScreen에 포함되도록 수정하였습니다.
=> 🔀 :: (#221) - GAuth 업데이트 적용

.idea/compiler.xml, .idea/kotlinc.xml, .idea/misc.xml, data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForAnonymousResponse.kt, design-system/src/main/java/com/msg/sms/design/component/item/TechStackItem.kt, design-system/src/main/java/com/msg/sms/design/component/text/TechStackRow.kt, design-system/src/main/java/com/msg/sms/design/component/text/TechStackTextComponent.kt, design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt, design-system/src/main/java/com/msg/sms/design/util/addTitle.kt, design-system/src/main/res/drawable/ic_top_end_arrow.xml, domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForAnonymous.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/AwardComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/ImportantTaskComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentInfoComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/data/AwardData.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/data/ProjectData.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/data/RelatedLinksData.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/link/LinkComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/link/RelatedLinksComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectListComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectorComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/main/data/StudentDetailData.kt, presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
디테일 페이지가 수정됨에 따라 퍼블리싱을 변경합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/b060a040-d9bd-4ed7-9e0e-45d5956de04b
여기 영상에 프로필이 나오지 않은 이유는 컴포넌트를 하나 덜 들어가서 그래요. 만약 스크린에서 실행해서 문제 생기면 바로 해결할게요
* 기존의 드림북 제거,
* 리스트 형태의 프로젝트 추가
* 수상 이력 추가
* 기존의 Title과 Spacer를 넣던 로직을 좀 더 간편하게 컴포넌트로 생성
* 저기에 API 부분이 어찌 될지 몰라서 일단 Todo 처리 해놓은 부분 수정해야함
* 그 지금 보면 heightIn이 계산을 하지 않고 대충 큰 수로 잡아놓은 경우들이 좀 있어서, 데이터가 어느정도 크기로 들어갈 지 확인해서 수정해야함.
=> 🔀 :: (#220) - modify detail page UI according to changed feature

buildSrc/src/main/java/Versions.kt
충돌나면서 중간에 예전 버전이 안지워진 듯 하네요.
지금처럼 분리하는 것도 좋지만, 많은 버전 업이 일어나면 문제가 또 생길 수 있으니 적당히 파일을 분리하는 편이 좋아보이네요
=> 🔀 ::  (#262) - version conflict resolve

design-system/src/main/java/com/msg/sms/design/modifier/smsClickable.kt, presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProjectPreviewInputComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
- 프로젝트 프리뷰 갤러리 방식을 다중선택으로 변경합니다.
- 프로젝트 프리뷰 갤러리 방식 다중선택으로 변경
- 기존 갤러리 접근인 GetContent에서 PickVisualMedia 방식으로 변경
- 사용자가 bounded 및 리플 크기를 지정할 수 있도록 smsClickable업데이트
https://github.com/GSM-MSG/SMS-Android/assets/80810303/89209a51-8f63-420e-bf2c-d86cbfc6b704
=> 🔀 :: (#270) - 프로젝트 프리뷰 갤러리 다중선택으로 변경

presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/certification/CertificationsComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/language/ForeignLanguagesComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/CertificationsSection.kt, presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ForeignLanguagesSection.kt
* 자격증의 정보를 관리하는 부분의 수정, 삭제, 추가 기능을 구현합니다.
* 외국어의 정보를 관리하는 부분의 수정, 삭제, 추가 기능을 구현합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/a9af4e61-d513-482f-8d70-152d7615c9ce
=> 🔀 :: (#279) - create the state of certification and foreign language section on my page

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
- 직접 입력한 전공이 서버에 전달되지 않는 문제 해결
- 선택된 전공 값이 "직접입력" 이라면 텍스트 필드에 직접 입력한 값을 보내도록 수정
```kotlin
enteredProfileData.major.takeIf { it != "직접입력" } ?: enteredProfileData.enteredMajor
```
- 프로젝트가 없다면 정보기입전 프로젝트 아이콘과 프리뷰 업로드의 response값을 검증하지 않도록 처리
=> 🔀 :: (#330) - 직접 입력한 전공이 서버에 전달되지 않는 문제 해결

data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentListResponse.kt, data/src/main/java/com/msg/sms/data/remote/dto/student/response/StudentInformation.kt
- 메인 페이지의 리스트가 나오지 않는 문제 해결
- StudentList 요청의 Response DTO에 SerializedName을 붙여 서버와 변수 이름을 맞췄습니다.
=> 🔀 :: (#332) - 메인 페이지의 리스트가 나오지 않는 문제 해결

presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentInfoComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/award/AwardComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/info/StudentInfoComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/detail/profile/StudentProfileComponent.kt
- 디테일 페이지 UI를 수정합니다.
- 디테일 학생 정보에 없던 헤더를 추가했습니다.
- 섹션별로 컴포넌트를 분리하고 패키징을 진행했습니다.
=> 🔀 :: (#344) - 디테일 페이지 UI수정

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt, presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/PhotoPickBottomSheet.kt
- 이미지 extension이 맞아야만 이미지 업로드 될 수 있도록 변경
- 기존의 이미지 extension이 맞으면 넘어온 uri를 넘기고 그렇지 않다면 Uri.EMPTY를 넘기던 방식에서 extension이 맞아야만 이미지 uri를 넘기도록 수정하였습니다.
```kotlin
PhotoPickBottomSheet(
bottomSheetState = bottomSheetState,
onProfileImageUriChanged = { uri, isImageExtensionCorrect ->
isImageExtensionInCorrect.value = !isImageExtensionCorrect
if (isImageExtensionCorrect) {
profileImageUri.value = uri
}
}
)
```
=> 🔀 :: (#355) - 이미지 extension이 맞아야만 이미지 업로드 될 수 있도록 변경

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt, presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileTechStackInputComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
- 프로필 세부스택 삭제 기능 구현
- 프로필 테크스택은 profileDetailTechStack이라는 변수를 참조하고 있지만 실제로는 ProfileData만 copy를 통해 지워주기 때문에 UI상에서 지워지지 않던 문제를 profileDetailTechStack도 삭제 버튼 클릭시 함께 값을 없애주도록 변경하여 문제를 해결함
```kotlin
onTechStackRemoved = { removedItem ->
onTechStackItemRemoved(removedItem)
onProfileValueChanged(data.copy(techStack = detailStacks.minus(removedItem)))
}
```
=> 🔀 :: (#358) - 프로필 세부스택 삭제 기능 구현

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/schoollife/SchoolLifeComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/util/extension.kt
- 인증제 점수의 " . " 과 " - "이 입력되던 문제를 해결합니다.
- 호이스팅으로 값을 넘겨줄때 replace를 통해 " . "을 공백으로 치환해주어 " . " 과 " - "모두 입력이 불가능하도록 작업하였습니다.
```kotlin
gsmAuthenticationScore(it.replace(".",""))
```
=> 🔀 :: (#362) - 인증제 점수 인풋 이슈 해결

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt, presentation/src/main/java/com/sms/presentation/main/ui/util/extension.kt
=> 🔀 :: (#376) - Change the regex on regular_expression

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/PhotoPickBottomSheet.kt
- 이미지 확장자 검사 boolean값 반대로 넘어오던 문제 해결
- 카메라 런쳐에서 boolean값을 넘겨주는 로직에 " ! "를 삭제합니다.
=> 🔀 :: (#378) - 이미지 확장자 검사 boolean값 반대로 넘어오던 문제 해결

presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectorComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectorGroup.kt, presentation/src/main/java/com/sms/presentation/main/ui/filter/screen/FilterScreen.kt, presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt, presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
- 학과 및 희망 고용형태 필터링이 진행되지 않던 문제 해결
- 학과 및 희망 고용형태 필터링 쿼리에 Enum값이 아닌 UI에 표시되는 문제를 해결했습니다.
- 데이터를 관리하는 List의 타입을 String에서 각각의 Enum으로 바꾸어 UI에서는 Enum의 value가 사용되도록, 서버에 요청을 보낼때는 enum값을 보내도록 변경하였습니다.
=> 🔀 :: (#382) - 학과 및 희망 고용형태 필터링이 진행되지 않던 문제 해결

presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt, presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt, presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt
- 메인페이지 리스트 페이지네이션 이슈 해결
- 학생 리스트를 뷰모델에서 관리하도록 변경
- 초기에는 액티비티에서 한번 리스트를 요청하고 이후에는 페이지네이션 로직에 따라 요청하도록 변경
- 필터페이지에서 필터링 정보 선택 후 확인 버튼을 누르면 전체 리스트를 지우고 다시 요청함
=> 🔀 :: (#388) - 메인페이지 리스트 페이지네이션 이슈 해결

.gitignore, presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt
AuthViewModel의 saveTokenRequest Event 안의 Data를 사용하지 않는데 타입으로 들어가 있는 이슈
```kotlin
private val _saveTokenRequest = MutableLiveData<Event<MajorListModel>>()
val saveTokenRequest: LiveData<Event<MajorListModel>> get() = _saveTokenRequest
// . . . .
fun saveTheLoginData(data: GAuthLoginResponseModel) = viewModelScope.launch {
saveTheLoginDataUseCase(
data = data
).onSuccess {
_saveTokenRequest.value = Event.Success()
}.onFailure {
_saveTokenRequest.value = it.errorHandling()
}
}
```
위의 saveTokenRequest를 사용하는 fun에서 Event 안의 MajorListModel를 사용하지 않는데 타입으로 들어가 있어 타입을 아래 처럼 Nothing으로 변경해주었습니다.
```kotlin
private val _saveTokenRequest = MutableLiveData<Event<Nothing>>()
val saveTokenRequest: LiveData<Event<Nothing>> get() = _saveTokenRequest
```
saveTokenRequest Type
제가 잘못 리팩토링했거나 컨벤션에 맞지 않는 부분이 있다면 …
=> 🔀 :: (#392) - AuthViewModel SaveToken 변수

presentation/src/main/AndroidManifest.xml, presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginScreen.kt, presentation/src/main/java/com/sms/presentation/main/ui/util/isBrowserInstalled.kt, presentation/src/main/res/values-ko/strings.xml, presentation/src/main/res/values/strings.xml
- 해외 기기에서 web브라우저가 존재하지 않을때 예외처리가 되지 않아 예외처리합니다.
- 안드로이드 장치에 설치된 브라우저 앱의 유무를 판단해서 예외를 처리합니다.
- 앱 패키지 정보 접근 권한 허용
- 예외 다이얼로그 문자열 다국어 처리(한국어, 영어)
- 브라우저의 유무를 판단하는 함수 추가
- GAuth 버튼이 클릭되었을때 함수를 실행해서 예외 처리
=> 🔀 :: (#409) - Exceptions when a web browser does not exist in an overseas device

data/src/main/java/com/msg/sms/data/remote/dto/student/request/PutChangedProfileRequest.kt, data/src/main/java/com/msg/sms/data/remote/dto/user/response/GetMyProfileResponse.kt, domain/src/main/java/com/msg/sms/domain/model/user/response/MyProfileModel.kt, presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/PortfolioComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/MyProfileData.kt
로그인한 유저의 마이페이지의 Response의 값이 null이 오는 경우가 생기는 곳을 찾아 nullable 처리 합니다.
PutChangedProfileRequest, GetMyProfileResponse 등 기존에 필수 값이 였던 것을 nullable 처리 합니다
- PutChangedProfileRequest.kt의 potfolioUrl
- GetMyProfileResponse.kt의 potfolioUrl
- MyProfileModel.kt의 potfolioUrl
- PotfolioComponent.kt 의 potfolioValue
- MyProfileData의 potfolioUrl
등이 nullable 처리 되었습니다
수정 사항에 따른 버튼의 활성화는 추가로 추가로 이슈를 생성할 계획입니다
=> 🔀 :: (#406) 로그인한 유저의 마이페이지 nullable 처리

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_authentication/FillOutAuthenticationScreen.kt, presentation/src/main/java/com/sms/presentation/main/ui/fill_out_authentication/component/ActivityDescriptionComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/fill_out_authentication/component/ActivityTitleComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/fill_out_authentication/component/PictureComponent.kt, presentation/src/main/java/com/sms/presentation/main/ui/fill_out_authentication/section/AuthenticationSection.kt, presentation/src/main/java/com/sms/presentation/main/ui/fill_out_authentication/state/AuthenticationData.kt
- 인증제 입력 페이지 퍼블리싱
- 인증제 입력 페이지를 퍼블리싱 했습니다.
=> 🔀 :: (#419) - publishing input authentication
