.github/workflows/android.yml
.github/workflows/android_ci.yml

github action으로 ci를 설정합니다. 
android build test, cache를 추가합니다

🔀 :: (#1) setting android ci

---

.github/workflows/android_ci.yml
app/build.gradle.kts
app/src/main/java/com/msg/sms_android/SmsApplication.kt
app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
build.gradle.kts
buildSrc/src/main/java/Dependency.kt
buildSrc/src/main/java/Versions.kt
data/build.gradle.kts
domain/build.gradle.kts
presentation/build.gradle.kts

- DI를 사용하기 위헤 세팅을 진행했습니다,
- Dagger Hilt의 의존성을 추가하였습니다
- NetworkModule을 작성했습니다.

🔀 :: (#8) - DI세팅

---

buildSrc/src/main/java/Dependency.kt
buildSrc/src/main/java/Versions.kt
presentation/build.gradle.kts
settings.gradle
settings.gradle.kts

🔀 :: (#10) - GAuth 의존성 추가

---

.gitignore
app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
data/src/main/java/com/msg/sms/data/remote/dto/auth/request/GAuthLoginRequest.kt
data/src/main/java/com/msg/sms/data/remote/dto/auth/response/GAuthLoginResponse.kt
data/src/main/java/com/msg/sms/data/remote/network/api/AuthAPI.kt

- GAuth로 로그인 remote쪽 로직 작성
- remote쪽의 AuthAPI를 작성했습니다.
- GAuth로 로그인을 위한 response와 request를 만들었습니다.
- NetWorkModule에 AuthAPI를 추가했습니다.

🔀 :: (#20) - GAuth로 로그인 remote쪽 로직 작성

---

app/src/main/java/com/msg/sms_android/modules/DataSourceModule.kt
app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
data/src/main/java/com/msg/sms/data/remote/datasource/auth/AuthDataSource.kt
data/src/main/java/com/msg/sms/data/remote/datasource/auth/AuthDataSourceImpl.kt
data/src/main/java/com/msg/sms/data/util/SMSApiHandler.kt
domain/src/main/java/com/msg/sms/domain/exception/HttpException.kt
domain/src/main/java/com/msg/sms/domain/exception/NeedLoginException.kt
domain/src/main/java/com/msg/sms/domain/exception/NoInternetException.kt

- GAuth로 로그인 data layer 로직 작성
- exception들과 ApiHandler를 추가하였습니다.
- dataSource와 dataSourceImpl을 작성하였습니다.
- DataSourceModule을 작성하였습니다.

🔀 :: (#22) - GAuth로 로그인 data layer 로직 작성

---

app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSource.kt
data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSourceImpl.kt

🔀 :: (#22) - 네이밍 변경

---

design-system/src/main/java/com/msg/sms/design/component/SmsChip.kt
design-system/src/main/res/drawable/plus_btn_icon.xml
presentation/src/main/AndroidManifest.xml

- design system의 chip component를 구현했습니다.
- design system모듈에 component 패키지 생성
- 생성한 패키지 안에 코드 작성
https://user-images.githubusercontent.com/80810303/236118195-f4aa298c-5f09-42eb-a9af-7739a071a057.mov
```kotlin
SmsChip(
icon = 아이콘 아이디,
text = 텍스트,
modifier = Modifier....
) {
//onClick
}
```
- SmsChip 함수를 호출하여 각 파라미터에 값을 넣어 사용합니다.
- text 파라미터에 String을 넣어 아이콘 옆의 텍스트를 설정할 수 있습니다.
- icon 파라미터에 Int형의 id값을 넣어 아이콘을 설정할 수 있습니다.
- onClick파라미터에서 클릭시 동작을 지정해줄 수 있습니다. 
- icon파라미터의 default값은 위 사진에 있던 plus button icon입니다. 
- modifier파라미터의 default값은 Modifier입니다.
- R.drawable.id명 으로 직접 사용한 icon은 추후 design system icon파트 제작 후에 design system코드를 사용하는것으로 변경할 예정입니다.

🔀 :: (#38) - design system chip component 구현

---

design-system/src/main/java/com/msg/sms/design/component/button/BoxButton.kt
design-system/src/main/java/com/msg/sms/design/component/button/ButtonState.kt
design-system/src/main/java/com/msg/sms/design/component/button/RoundedButton.kt
design-system/src/main/java/com/msg/sms/design/theme/SMSTheme.kt

버튼을 스타일에 따라 사용할 수 있도록 구현하였습니다.
https://user-images.githubusercontent.com/82383983/236594621-eaef9d4a-3146-4655-994e-cb7c9bf32cdc.mov

🔀 :: (#37) - add button component

---

design-system/src/main/java/com/msg/sms/design/component/selector/SmsSelectionControls.kt

디자인 시스템의 라디오 버튼을 구현합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/dd67996c-e13c-42a0-b6e4-235aa426431c

🔀 :: (#48) - create component of selector button

---

design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt

- 아이콘 컴포넌트 사용시 색이 전부 회색으로 나오던 이슈를 해결했습니다.
- 아이콘 컴포넌트 구현 방식을 icon 에서 image로 변경했습니다.

🔀 :: (#58) - 아이콘 색 이슈 해결

---

design-system/src/main/java/com/msg/sms/design/component/indicator/PagerIndicator.kt
design-system/src/main/java/com/msg/sms/design/component/spacer/SmsSpacer.kt
design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
design-system/src/main/java/com/msg/sms/design/component/topbar/TopBarComponent.kt
design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
design-system/src/main/res/drawable/ic_profile_btn.xml
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/ProfileScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/TopBarComponent.kt

정보를 입력하는 페이지 중, 프로필 페이지를 퍼블리싱합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/2b508280-9bea-49e9-8315-835bc735835f

🔀 :: (#51) - publishing the profile page UI of fill out infomation

---

design-system/src/main/java/com/msg/sms/design/component/text/SmsTitleText.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/SchoolLifeScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/SchoolLifeComponent.kt

학교 생활 페이지를 퍼블리싱합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/f9676b94-78ca-49fb-bd0e-022d347ba342

🔀 :: (#52) - publishing the page of school life

---

design-system/src/main/java/com/msg/sms/design/component/bottomsheet/SelectorBottomSheet.kt
design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
design-system/src/main/res/drawable/ic_trash_can.xml
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/ProfileScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/WorkConditionScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt

정보 기입 페이지 중, 근무 조건을 나타내는 페이지를 퍼블리싱합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/441da8d6-9db1-401f-9422-8edbff0dd99a

🔀 :: (#53) - publishing the working condition page UI of fill out information

---

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/MilitaryServiceScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/MilitaryServiceComponent.kt

병역 관련 정보를 입력하는 페이지를 퍼블리싱합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/ff848e8e-5d66-4561-bbdd-9feec008312d

🔀 :: (#54) - create militaryService Page

---

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/ForeignLanguageScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt

정보 기입 중 외국어 관련 정보를 기입하는 페이지를 퍼블리싱합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/a12f6057-e341-4745-a8ae-4fe1867637a0

🔀 :: (#56) - create ForeignLanguageScreen

---

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/CertificationScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/CertificationComponent.kt

정보 기입 페이지 중 자격증 페이지를 퍼블리싱합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/1b076884-32a9-4f77-988d-fba45241464a

🔀 :: (#55) - create certificationScreen

---

app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
app/src/main/java/com/msg/sms_android/modules/RepositoryModule.kt
data/src/main/java/com/msg/sms/data/remote/datasource/fileupload/RemoteFileUploadDataSource.kt
data/src/main/java/com/msg/sms/data/remote/datasource/fileupload/RemoteFileUploadDataSourceImpl.kt
data/src/main/java/com/msg/sms/data/remote/dto/file/response/FileUploadResponse.kt
data/src/main/java/com/msg/sms/data/remote/dto/fileupload/response/FileUploadResponse.kt
data/src/main/java/com/msg/sms/data/remote/network/api/FileUploadAPI.kt
data/src/main/java/com/msg/sms/data/repository/FileUploadRepositoryImpl.kt
domain/build.gradle.kts
domain/src/main/java/com/msg/sms/domain/model/fileupload/response/FileUploadResponseModel.kt
domain/src/main/java/com/msg/sms/domain/repository/FileUploadRepository.kt
domain/src/main/java/com/msg/sms/domain/usecase/fileupload/ImageUploadUseCase.kt
presentation/build.gradle.kts
presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/FileUploadViewModel.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentViewModel.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/util/Event.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/util/errorHandling.kt

- 이미지 업로드 로직을 작성했습니다
- flow를 활용하여 전체적인 로직 작성
- @Binds를 통한 di작성
- util파일중 Event에서 Success일 경우 데이터를 넘겨받도록 수정함
- Event파일 변경에 따라 errorHandling파일도 수정됨
- Event파일 변경에 따라 기존에 있던 두개의 뷰모델 파일도 수정됨

🔀 :: (#76) - 이미지 업로드 로직 작성

---

design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/SchoolLifeComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/MilitaryServiceData.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ProfileData.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/WorkConditionData.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/CertificationScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ForeignLanguageScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/MilitaryServiceScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/WorkConditionScreen.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentViewModel.kt

데이터를 저장하여 보여주고, 버튼을 제어하도록 설정합니다.

🔀 :: (#83) - save information entered by users

---

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/CertificationComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/CertificationData.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/CertificationScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ForeignLanguageScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/WorkConditionScreen.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentViewModel.kt

리스트 형태의 데이터들을 저장합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/19e194a7-096c-421d-83ed-25514e651016

🔀 - 88 store and loading list data of entered by user

---

data/src/main/java/com/msg/sms/data/remote/dto/auth/response/GAuthLoginResponse.kt
domain/src/main/java/com/msg/sms/domain/model/auth/response/GAuthLoginResponseModel.kt
presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt

로그인 하였을 때 유저의 상태에 따라서 화면을 제어합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/7b9ecf88-a5b8-4f9d-bf8e-151ebc1cdef0

🔀 :: (#92) - when login control the page according to type of user

---

app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
app/src/main/java/com/msg/sms_android/modules/RepositoryModule.kt
data/src/main/java/com/msg/sms/data/remote/datasource/major/RemoteMajorDataSource.kt
data/src/main/java/com/msg/sms/data/remote/datasource/major/RemoteMajorDataSourceImpl.kt
data/src/main/java/com/msg/sms/data/remote/dto/major/MajorListResponse.kt
data/src/main/java/com/msg/sms/data/remote/network/api/MajorAPI.kt
data/src/main/java/com/msg/sms/data/repository/MajorRepositoryImpl.kt
data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
domain/src/main/java/com/msg/sms/domain/model/major/MajorListModel.kt
domain/src/main/java/com/msg/sms/domain/repository/MajorRepository.kt
domain/src/main/java/com/msg/sms/domain/usecase/major/GetMajorListUseCase.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/CertificationComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/CertificationScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ForeignLanguageScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/MilitaryServiceScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/WorkConditionScreen.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt

🔀 :: (#93) - get major list from server

---

data/src/main/java/com/msg/sms/data/repository/AuthRepositoryImpl.kt
data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
domain/src/main/java/com/msg/sms/domain/repository/AuthRepository.kt
domain/src/main/java/com/msg/sms/domain/usecase/auth/SaveTheLoginDataUseCase.kt
presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt

* 로그인 성공 시 토큰 저장
* 액세스 토큰 포함 시키기

🔀 :: ($98) - store the login data

---

data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
design-system/src/main/java/com/msg/sms/design/component/bottomsheet/SelectorBottomSheet.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ProfileData.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt

Resurrection like a dog!!
https://github.com/GSM-MSG/SMS-Android/assets/82383983/a9ae769d-994e-4522-994a-d67e23784113

🔀 :: (#100) - add the ability to populate other majors

---

presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt

https://github.com/GSM-MSG/SMS-Android/assets/82383983/fee1cbdb-f273-4594-a62f-3432b9116fa0

🔀 :: (#108) - auto login check

---

data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt

- 프로필 정보기입 bottom sheet이슈 해결
- Image의 onClick에서도 isProfilePictureBottomSheet 변수의 값을 true로 지정해 줄 수 있도록 코드 작성
- 실제 테스팅 필요

🔀 :: (#105) - 프로필 정보기입 bottom sheet이슈 해결

---

data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
data/src/main/java/com/msg/sms/data/util/DateFormatter.kt

🔀 :: (#112) - modify login time format

---

app/src/main/res/values/themes.xml
data/src/main/java/com/msg/sms/data/util/AuthInterceptor.kt
presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/util/setTransparentStatusBar.kt

* status bar color 변경
* interceptor error 수정
https://github.com/GSM-MSG/SMS-Android/assets/82383983/dd0003ec-8cd8-490a-a60b-ef5bd9e38300

🔀 :: (#114) - change the status bar color

---

presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginButton.kt
presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/login/component/LookAroundToGuestButton.kt

🔀 :: (#128) - 게스트로 이동 버튼 추가

---

data/src/main/java/com/msg/sms/data/remote/dto/student/response/StudentInformation.kt
domain/src/main/java/com/msg/sms/domain/model/student/response/StudentModel.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt

🔀 :: (#125) - 필드명 변경

---

data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSource.kt
data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSourceImpl.kt
data/src/main/java/com/msg/sms/data/remote/dto/auth/response/AccessValidationResponse.kt
data/src/main/java/com/msg/sms/data/remote/network/api/AuthAPI.kt
data/src/main/java/com/msg/sms/data/repository/AuthRepositoryImpl.kt
domain/src/main/java/com/msg/sms/domain/model/auth/response/AccessValidationResponseModel.kt
domain/src/main/java/com/msg/sms/domain/repository/AuthRepository.kt
domain/src/main/java/com/msg/sms/domain/usecase/auth/AccessValidationUseCase.kt
presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt

- 자동로그인 로직 변경
- isExist를 받아 정보기입을 한 유저인지 파악 후 boolean 값에 따라 정보기입, 메인 페이지로 이동하도록 수정
- access 유효성 검사 api가 생김에 따라 major list 요청으로 자동로그인을 검사하던걸 수정했습니다.

🔀 :: (#132) - 자동로그인 변경

---

app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
app/src/main/java/com/msg/sms_android/modules/RepositoryModule.kt
data/src/main/java/com/msg/sms/data/remote/datasource/stack/RemoteStackDataSource.kt
data/src/main/java/com/msg/sms/data/remote/datasource/stack/RemoteStackDataSourceImpl.kt
data/src/main/java/com/msg/sms/data/remote/dto/stack/reponse/SearchingDetailStackResponse.kt
data/src/main/java/com/msg/sms/data/remote/network/api/StackAPI.kt
data/src/main/java/com/msg/sms/data/repository/StackRepositoryImpl.kt
design-system/src/main/java/com/msg/sms/design/component/SearchBar.kt
design-system/src/main/java/com/msg/sms/design/component/topbar/SearchTopBar.kt
domain/src/main/java/com/msg/sms/domain/model/stack/DetailStackListModel.kt
domain/src/main/java/com/msg/sms/domain/repository/StackRepository.kt
domain/src/main/java/com/msg/sms/domain/usecase/stack/GetSearchDetailStackUseCase.kt
presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/RecentlyAddedListComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/SearchDetailStackViewModel.kt

세부 전공 검색 및 선택 페이지 구현
https://github.com/GSM-MSG/SMS-Android/assets/82383983/201962d3-733e-44da-8cc1-daa28d1601be

🔀 :: (#127) - import the data of stack when user searching

---

app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
app/src/main/java/com/msg/sms_android/modules/RepositoryModule.kt
data/src/main/java/com/msg/sms/data/remote/datasource/stack/RemoteStackDataSource.kt
data/src/main/java/com/msg/sms/data/remote/datasource/stack/RemoteStackDataSourceImpl.kt
data/src/main/java/com/msg/sms/data/remote/dto/stack/reponse/SearchingDetailStackResponse.kt
data/src/main/java/com/msg/sms/data/remote/network/api/StackAPI.kt
data/src/main/java/com/msg/sms/data/remote/network/api/StudentAPI.kt
data/src/main/java/com/msg/sms/data/repository/StackRepositoryImpl.kt
data/src/main/java/com/msg/sms/data/util/SMSApiHandler.kt
design-system/src/main/java/com/msg/sms/design/component/SearchBar.kt
design-system/src/main/java/com/msg/sms/design/component/topbar/SearchTopBar.kt
domain/src/main/java/com/msg/sms/domain/model/stack/DetailStackListModel.kt
domain/src/main/java/com/msg/sms/domain/repository/StackRepository.kt
domain/src/main/java/com/msg/sms/domain/usecase/stack/GetSearchDetailStackUseCase.kt
presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/RecentlyAddedListComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/SearchDetailStackViewModel.kt

- 정보기입 예외가 잡히지 않는 문제를 해결합니다.
- 정보기입 Api에서 Response타입 삭제
- 400, 409에 대한 추가 예외처리 진행

🔀 :: (#131) - 정보기입 예외가 잡히지 않는 문제 해결

---

data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSource.kt
data/src/main/java/com/msg/sms/data/remote/datasource/student/RemoteStudentDataSourceImpl.kt
data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForAnonymousResponse.kt
data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForStudentResponse.kt
data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForTeacherResponse.kt
data/src/main/java/com/msg/sms/data/remote/network/api/StudentAPI.kt
data/src/main/java/com/msg/sms/data/repository/StudentRepositoryImpl.kt
domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForAnonymous.kt
domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForStudent.kt
domain/src/main/java/com/msg/sms/domain/model/student/response/GetStudentForTeacher.kt
domain/src/main/java/com/msg/sms/domain/repository/StudentRepository.kt
domain/src/main/java/com/msg/sms/domain/usecase/student/GetStudentDetailForStudentUseCase.kt
domain/src/main/java/com/msg/sms/domain/usecase/student/GetUserDetailForAnonymousUseCase.kt
domain/src/main/java/com/msg/sms/domain/usecase/student/GetUserDetailForTeacherUseCase.kt

setting for the API connecting

🔀 :: (#138) - setting the api that import user detail imformation

---

data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSource.kt
data/src/main/java/com/msg/sms/data/remote/datasource/auth/RemoteAuthDataSourceImpl.kt
data/src/main/java/com/msg/sms/data/remote/network/api/AuthAPI.kt
data/src/main/java/com/msg/sms/data/repository/AuthRepositoryImpl.kt
design-system/src/main/java/com/msg/sms/design/component/item/RecentlyAddedItem.kt
domain/src/main/java/com/msg/sms/domain/repository/AuthRepository.kt
domain/src/main/java/com/msg/sms/domain/usecase/auth/DeleteTokenUseCase.kt
domain/src/main/java/com/msg/sms/domain/usecase/auth/LogoutUseCase.kt
domain/src/main/java/com/msg/sms/domain/usecase/auth/WithdrawalUseCase.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt

* 로그아웃 api 구현
* 계정탈퇴 api 구현
* 로컬 DB에 계정 정보 제거 로직 구현
* 로그인 로직 flow로 리팩토링

🔀 :: (#144) - setting the api of withdrawal and logout

---

data/src/main/java/com/msg/sms/data/remote/dto/student/response/StudentInformation.kt
domain/src/main/java/com/msg/sms/domain/model/student/response/StudentModel.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/component/LogoutWithDrawalBottomSheetComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt

- 아이템 클릭시 디테일 페이지 뜨도록 설정
- ModalBottomSheet으로 작업

🔀 :: (#142) - 아이템 클릭시 디테일 페이지 뜨도록 설정

---

presentation/src/main/AndroidManifest.xml
presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/util/downloader/AndroidDownloader.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/util/downloader/DownloadCompletedReceiver.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/util/downloader/Downloader.kt

🔀 :: (#146) - download the file of dream book when click dream book icon

---

presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListItem.kt

🔀 :: (#152) - convert the name from star to 소금

---

design-system/src/main/java/com/msg/sms/design/component/item/RecentlyAddedItem.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/RecentlyAddedListComponent.kt

when typing a keyword, change the text color of matched

🔀 :: (#156) - when typing keyword, change text color of matched

---

presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentInfoComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/data/StudentDetailData.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/util/extension.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt

- 디테일 페이지에서 바텀시트를 올리고 디테일을 닫을 시에 다시 켜면 바텀시트가 올라와있는 상태로 남아있는 문제 해결
- 바텀시트를 닫는 버튼을 눌렀을 때 스크롤 안된 상태로 되돌아가게 지정

🔀 :: (#148) - 디테일 페이지 바텀시트 이슈 해결

---

data/src/main/java/com/msg/sms/data/local/datasource/auth/LocalAuthDataSource.kt
data/src/main/java/com/msg/sms/data/local/datasource/auth/LocalAuthDataSourceImpl.kt
data/src/main/java/com/msg/sms/data/local/key/AuthPreferenceKey.kt
data/src/main/java/com/msg/sms/data/remote/dto/auth/response/GAuthLoginResponse.kt
data/src/main/java/com/msg/sms/data/repository/AuthRepositoryImpl.kt
domain/src/main/java/com/msg/sms/domain/model/auth/response/GAuthLoginResponseModel.kt
domain/src/main/java/com/msg/sms/domain/repository/AuthRepository.kt
domain/src/main/java/com/msg/sms/domain/usecase/auth/GetRoleInfoUseCase.kt
domain/src/main/java/com/msg/sms/domain/usecase/auth/SaveRoleInfoUseCase.kt
presentation/src/main/java/com/sms/presentation/main/ui/login/LoginActivity.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt

- Role 관련 정보 로컬 디비에 저장
- 로그인 성공시에 role관련 정보들 저장하도록 처리
- 로그인 관련 response dto들에 role이 없어서 추가함.

🔀 :: (#160) - Role 관련 정보 로컬 디비에 저장

---

presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt

- 저장한 Role정보에 따라 UI다르게 표시하도록 처리
- 게스트일 경우 프로필 버튼 누르면 바로 로그인 페이지로 가도록 처리
- 디테일 페이지 자기소개 부분 바뀐 디자인 반영

🔀 :: (#162) - 저장한 Role정보에 따라 UI다르게 표시하도록 처리

---

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/login/component/LoginScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/login/component/ShowTheTermsOfUse.kt

수정함
https://github.com/GSM-MSG/SMS-Android/assets/82383983/8eaa9e4a-fd5c-430e-b8df-52130acb3ded

🔀 :: (#167) - add the terms of use and remove the topbar icon

---

design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/component/StudentListItem.kt

🔀 :: (#172) - change the color of cursors

---

design-system/src/main/java/com/msg/sms/design/component/SearchBar.kt
design-system/src/main/java/com/msg/sms/design/component/SmsChip.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/RecentlyAddedListComponent.kt

🔀 :: (#174) - add self insert the detail stack

---

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt

🔀 :: (#178) - control the keyboard position

---

app/src/main/java/com/msg/sms_android/modules/NetworkModule.kt
app/src/main/java/com/msg/sms_android/modules/RemoteDataSourceModule.kt
app/src/main/java/com/msg/sms_android/modules/RepositoryModule.kt
data/src/main/java/com/msg/sms/data/remote/datasource/user/RemoteUserDataSource.kt
data/src/main/java/com/msg/sms/data/remote/datasource/user/RemoteUserDataSourceImpl.kt
data/src/main/java/com/msg/sms/data/remote/dto/user/response/GetProfileImageResponse.kt
data/src/main/java/com/msg/sms/data/remote/network/api/UserAPI.kt
data/src/main/java/com/msg/sms/data/repository/UserRepositoryImpl.kt
domain/src/main/java/com/msg/sms/domain/model/user/response/ProfileImageModel.kt
domain/src/main/java/com/msg/sms/domain/repository/UserRepository.kt
domain/src/main/java/com/msg/sms/domain/usecase/user/GetProfileImageUseCase.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/component/MainScreenTopBar.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt

- 프로필 이미지 가져오는 작업
- 프로필 이미지 가져오는 로직 작성
- 프로필 이미지 contentScale 맞추기

🔀 :: (#181) - 프로필 이미지 가져오는 작업

---

presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/util/downloader/AndroidDownloader.kt

🔀 :: (#184) - control the screen according to keyboard

---

presentation/src/main/java/com/sms/presentation/main/viewmodel/util/downloader/AndroidDownloader.kt

- 다운로드된 파일 확장자 이슈 해결
- 다운로드 매니저에 한글 mime타입 추가

🔀 :: (#186) - 다운로드된 파일 확장자 이슈 해결

---

presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/util/extension.kt

- 파일 업로드 관련 이슈 해결
- 파일 확장자 검사 방식을 기본 제공 함수로 변경
- 다운로드시 파일 이름 뒤에 hwp붙여주도록 설정

🔀 :: (#186) - 파일 업로드 관련 이슈 해결

---

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt

🔀 :: (197) - change the wanted payroll

---

design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
design-system/src/main/res/drawable/ic_exclamation_mark.xml
presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt

- 필터 버튼 클릭시 이벤트 추가
- 필터 버튼 클릭시 개발중이라고 알려주는 스낵바가 뜨도록 처리

🔀 :: (#194) - 필터 버튼 클릭시 이벤트 추가

---

presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ProfileComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/WorkConditionComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/util/textFieldChecker.kt

🔀 :: (#196) - change the textfield checker

---

design-system/src/main/java/com/msg/sms/design/component/topbar/TopBarComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/CertificationScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ForeignLanguageScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/MilitaryServiceScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/SchoolLifeScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/WorkConditionScreen.kt

탑바에 있는 백버튼 클릭 시 페이지를 백스택으로 이동시키고, 파라미터를 일반적으로 더 자주사용하는 left icon clicker가 편리하게 이용되도록 순서를 변경하였습니다.

🔀 :: (#193) - change page when click top bar button

---

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt

뒤로 가기 버튼을 2번 클릭하였을 때 앱을 종료시킵니다.

🔀 :: (#195) - control the app stack when click the back button

---

design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt

- 외국어 점수 텍스트 필드에 singleLine을 추가합니다
- 커스텀 텍스트 필드에 singleLine Boolean 파라미터 추가

🔀 :: (#189) - 외국어 점수 텍스트 필드에 singleLine 추가

---

design-system/src/main/java/com/msg/sms/design/component/SmsDialog.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/util/extension.kt

- 이메일, Url 정규식 검사 추가
- 프로필에서 다음 버튼을 눌렀을 때 정규식을 검사하도록 처리
- 만약 정규식을 뚫고 서버에서 정규식 관련 문제가 발생하여 400이 날 경우 경우에 맞는 예외처리 진행
- 디자인 시스템의 다이얼로그에 텍스트와 버튼 사이 간격 조절할 수 있도록 파라미터 추가

🔀 :: (#192) - 이메일, Url 정규식 검사 추가

---

design-system/src/main/java/com/msg/sms/design/component/SmsDialog.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt

🔀 :: (#211) - 취소버튼 없앨 수 있도록 로직 추가

---

data/src/main/java/com/msg/sms/data/remote/datasource/user/RemoteUserDataSource.kt
data/src/main/java/com/msg/sms/data/remote/datasource/user/RemoteUserDataSourceImpl.kt
data/src/main/java/com/msg/sms/data/remote/dto/user/response/GetMyProfileResponse.kt
data/src/main/java/com/msg/sms/data/remote/dto/user/response/LanguageCertificateResponse.kt
data/src/main/java/com/msg/sms/data/remote/network/api/UserAPI.kt
data/src/main/java/com/msg/sms/data/repository/UserRepositoryImpl.kt
domain/src/main/java/com/msg/sms/domain/model/user/response/LanguageCertificateModel.kt
domain/src/main/java/com/msg/sms/domain/model/user/response/MyProfileModel.kt
domain/src/main/java/com/msg/sms/domain/repository/UserRepository.kt
domain/src/main/java/com/msg/sms/domain/usecase/user/GetMyProfileUseCase.kt

🔀 :: (#214) - create the model of my page data

---

.github/workflows/android_cd.yml

CD 스크립트 수정
다른 사람들의 스크립트를 참고하여 일부 수정하였습니다.
- 각 스크립트의 진행 순서 변경
-  aab upload 추가
- service_json_plain_text -> 이미 생성된 순수 파일을 적용시키는것으로 변경
궁금한 사항이 있다면 물어봐주세용.

🔀 : :: CD 스크립트 수정

---

.github/workflows/android_cd.yml

패키지명 수정
아무도 지적하지 않았던 패키지명을 수정해보았습니다.

🔀 :: 패키지 명 수정

---

design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
design-system/src/main/res/drawable/ic_gray_logout_btn.xml
presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/button/LogoutButton.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/button/WithdrawalButton.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/modal/MyPageBottomSheet.kt

* 메인페이지에 바텀 시트를 구현합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/859bacb5-9487-47c6-97d1-446c3d91d961

🔀 :: (#258) - create my page bottom sheet

---

design-system/src/main/java/com/msg/sms/design/component/header/TitleHeader.kt
design-system/src/main/java/com/msg/sms/design/icon/SmsIcon.kt
design-system/src/main/res/drawable/ic_chevron_down.xml
design-system/src/main/res/drawable/ic_chevron_left.xml
presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardNameComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardTypeComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectNameComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/AwardSection.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProjectsSection.kt

프로젝트와 수상을 sticky 헤더로 프로젝트와 수상 수에 따라 생성합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/c88d24f3-9f4e-4dd1-8d08-f08228a60076

🔀 :: (#264) - create toggle on my page

---

buildSrc/src/main/java/Dependency.kt
buildSrc/src/main/java/Versions.kt
design-system/build.gradle.kts
design-system/src/main/java/com/msg/sms/design/component/picker/DatePicker.kt
design-system/src/main/java/com/msg/sms/design/component/picker/SmsDatePicker.kt
design-system/src/main/java/com/msg/sms/design/theme/SMSTypography.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt

- DatePicker를 제작합니다.
- DatePicker제작
https://github.com/GSM-MSG/SMS-Android/assets/80810303/d14ae54f-be82-4862-b625-66d2330a2a7e
- 라이브러리에서 나오는 텍스트 FontWeight를 지정하기 위해 디자인 시스템의 pretendard 변수를 internal로 변경
- 라이브러리가 맘에 안듦

🔀 :: (#268) - Date Picker 제작

---

design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/life/SchoolScoreComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/SchoolLifeSection.kt

마이 페이지에서 인증제 점수를 입력하고, 기존 값을 설정해주도록 기능을 추가합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/4e501254-d587-40f6-b91d-e6a1202dd41b
숫자가 아닌 다른 것들이 들어와서 예외를 발생시키는 경우를 제거하였습니다.

🔀 :: (#276) - create data state of school life section on my page

---

presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/work/WantPayComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/work/WantWorkFormComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/work/WorkLocationComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/WorkConditionSection.kt

근무 조건과 관련된 정보를 저장하고 수정하는 부분을 작성합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/12f32dbd-527f-4170-a286-282abb980f2c

🔀 :: (#277) - create the state of working condition section on my page

---

presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/military/MilitaryServiceTypeComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/MilitaryServiceSection.kt

* 병역 희망 여부를 체크하는 바텀 시트를 완성합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/44be36f3-b8ca-4887-ba0c-b44bc6b08d0e

🔀 :: (#278) - create the state of military section on my page

---

design-system/src/main/java/com/msg/sms/design/component/header/TitleHeader.kt
design-system/src/main/java/com/msg/sms/design/component/indicator/PreviewImageIndicator.kt
design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
design-system/src/main/res/drawable/ic_gallery_btn.xml
presentation/src/main/java/com/sms/presentation/main/ui/detail/data/AwardNameData.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail/data/ExpandableProjectData.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail/data/ProjectNameData.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectIconComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectKeyTaskComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectNameComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectPreviewComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectRelatedLinksComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectTechStackComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProjectsSection.kt

🔀 :: (#285) - implement the feature of managing project data section on my page

---

design-system/src/main/java/com/msg/sms/design/component/SmsDialog.kt
design-system/src/main/java/com/msg/sms/design/component/button/BoxButton.kt
design-system/src/main/java/com/msg/sms/design/component/button/ButtonState.kt
design-system/src/main/java/com/msg/sms/design/component/button/RoundedButton.kt
design-system/src/main/java/com/msg/sms/design/component/textfield/SmsTextField.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/ForeignLanguageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/DetailTechStackComponent.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/AuthViewModel.kt

🔀 :: (#292) - create an account withdrawal and logout feature

---

presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/SearchDetailStackViewModel.kt

세부 스택을 검색을 재사용하기 위해 파라미터를 수정합니다.

🔀 ::(#295) - Change the parameter to reuse component to use the detail stack search 

---

presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardDateComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardNameComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardTypeComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/AwardSection.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProjectsSection.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/ExpandableAwardDate.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/ExpandableProjectData.kt

* 수상의 데이터 상태를 관리하는 state를 구성합니다
* 수상을 관리하는 데이터클래스의 변경이 생김

🔀 :: (#298) - create the data state of award on mypage

---

design-system/src/main/java/com/msg/sms/design/component/picker/SmsDatePicker.kt
design-system/src/main/java/com/msg/sms/design/component/picker/SmsNumberPicker.kt
design-system/src/main/java/com/msg/sms/design/component/picker/SmsPicker.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsComponent.kt

- Date Picker 및 일반 Picker를 제작합니다.
https://github.com/GSM-MSG/SMS-Android/assets/80810303/5477bf0c-afa3-4753-9dd9-9d4d7036f438
- 가운데로 아이템 고정되는건 업데이트때 하도록 하겠습니다.

🔀 :: (#290) - Date Picker 제작

---

buildSrc/src/main/java/Dependency.kt
buildSrc/src/main/java/Versions.kt
design-system/build.gradle.kts
design-system/src/main/java/com/msg/sms/design/component/bottomsheet/ChooseProfilePictureBottomSheet.kt
design-system/src/main/java/com/msg/sms/design/component/picker/SmsDatePicker.kt
design-system/src/main/java/com/msg/sms/design/component/picker/SmsPicker.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/FillOutInformationTopBarComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/DatePickerBottomSheet.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/MajorSelectorBottomSheet.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/MilitarySelectorBottomSheet.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/bottomsheet/PhotoPickBottomSheet.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/militaryservice/MilitaryServiceComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectIconInputComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectTechStackInputComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsBottomButtonComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/workcondition/WorkConditionComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/MilitaryServiceScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/WorkConditionScreen.kt

- 바텀 시트 관련 로직 리팩토링
- 바텀시트를 각 screen에서 관리하던걸 activity에서 뷰를 그리고 데이터를 각 screen으로 넘겨주는 방식으로 변경했습니다.

🔀 :: (#302) - 바텀 시트 관련 로직 리팩토링

---

data/src/main/java/com/msg/sms/data/remote/dto/stack/reponse/SearchingDetailStackResponse.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail_stack_search/DetailStackSearchScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/filter/screen/FilterScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/profile/DetailTechStackComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectTechStackComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProfileSection.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProjectsSection.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/ExpandableProjectData.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/state/ProjectTechStack.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/SearchDetailStackViewModel.kt

검색페이지의 요소들을 여러 페이지에서 사용할 수 있도록 구현하였습니다.

🔀 :: (#300) - create the feature of detail stack searching

---

presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt

🔀 :: (#307) - get major list data on my page

---

gradle.properties
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/profile/ProfileTechStackInputComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProfileScreen.kt

- 정보기입 프로필 부분 세부스택 그리드로 변경
- 정보기입 프로필 세부스택 컴포넌트 생성
- 정보기입 프로필 세부스택 삭제 기능 구현
- 프로필 세부스택을 액티비티에서 관리하기 위해 파라미터들 추가

🔀 :: (#296) - 정보기입 프로필 부분 세부스택 그리드로 변경

---

presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail/data/ProjectData.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail/project/ProjectListComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/project/ProjectDescriptionComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/ProjectsSection.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/MyProfileViewModel.kt

프로젝트 설명을 저장하는 컴포넌트를 저장합니다.
https://github.com/GSM-MSG/SMS-Android/assets/82383983/d89964bc-df09-4769-887b-53a5a14fed21

🔀 :: (#311) - create component of not added project imformation

---

design-system/src/main/java/com/msg/sms/design/component/bottomsheet/DatePickerBottomSheet.kt
design-system/src/main/java/com/msg/sms/design/component/picker/SmsDatePicker.kt
design-system/src/main/java/com/msg/sms/design/component/picker/SmsPicker.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt

🔀 :: (#324) - date picker 디자인 시스템에 생성

---

data/src/main/java/com/msg/sms/data/remote/dto/student/request/EnterStudentInformationRequest.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/award/AwardComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/foreignlanguage/ForeignLanguageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/AwardData.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ForeignLanguageInfo.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ForeignLanguagesData.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/AwardScreen.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/FillOutViewModel.kt

- 정보기입한 데이터를 모아서 서버에 전송합니다.
- 이미지 업로드를 프로필, 아이콘, 프리뷰 세 파트로 나누어서 비동기적으로 업로드 하고 3 요청이 모두 끝난 시점에 정보기입 요청을 전송합니다.
- 이미지 업로드와 정보기입에서 예외처리를 진행하였습니다.

🔀 :: (#310) - 정보기입한 데이터를 서버에 전송

---

data/src/main/java/com/msg/sms/data/remote/dto/student/request/ProjectDateData.kt
domain/src/main/java/com/msg/sms/domain/model/student/request/ProjectDateModel.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/projects/ProjectsComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/data/ProjectInfo.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/screen/ProjectsScreen.kt

- 프로젝트가 진행중임에도 endDate를 서버에 함께 전송하던 문제 해결
- dto endDate nullable로 변경
- 보내는 쪽에 if문 추가
- 프로젝트 진행중 Boolean 데이터도 프로젝트 list에서 관리하도록 변경

🔀 :: (#328) - 프로젝트 날짜 관련 이슈 해결

---

presentation/src/main/java/com/sms/presentation/main/ui/main/screen/MainScreen.kt

- 바텀시트 이슈 해결
- 디테일 페이지 오픈시 바텀시트가 반만 열리던 문제를 전체화면이 다 열리도록 로직 작성

🔀 :: (#338) - 바텀 시트 이슈 해결

---

presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt

- 필터가 기본값 value인 경우엔 null을 보냅니다.
```kotlin
minGsmAuthenticationScore = gsmScoreSliderValues.value.start.toInt().takeIf { it != 0 },
maxGsmAuthenticationScore = gsmScoreSliderValues.value.endInclusive.toInt().takeIf { it != 990 },
minSalary = desiredAnnualSalarySliderValues.value.start.toInt().takeIf { it != 0 },
maxSalary = desiredAnnualSalarySliderValues.value.endInclusive.toInt().takeIf { it != 9999 },
```

🔀 :: (#339) - 필터 기본값 보내지 않도록 로직 변경

---

presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectionControlsGroup.kt
presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSelectorGroup.kt
presentation/src/main/java/com/sms/presentation/main/ui/filter/component/FilterSliderGroup.kt
presentation/src/main/java/com/sms/presentation/main/ui/filter/screen/FilterScreen.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt
presentation/src/main/java/com/sms/presentation/main/viewmodel/StudentListViewModel.kt

- 필터에서 선택된 값들을 확인을 눌렀을 경우에만 보내도록 처리합니다.
- 필터에서 선택한 후에 닫기 버튼으로 나가도 필터링이 적용되는 문제를 해결했습니다.
- 선택한 변수와 실제 필터링에 사용되는 변수를 구분지어 해결하였습니다.

🔀 :: (#343) - 필터 적용 이슈 해결

---

data/src/main/java/com/msg/sms/data/remote/dto/stack/reponse/SearchingDetailStackResponse.kt
domain/src/main/java/com/msg/sms/domain/model/stack/DetailStackListModel.kt
presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/FillOutInformationActivity.kt
presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt

- 정보기입 세부스택 입력한 값 안나오는 에러 수정
- 이벤트가 성공했음에도 when문에서 감지하지 못하던 에러 해결
- when안쪽의 조건문을 is Event.Success로 변경해줌

🔀 :: (#347) - 정보기입 세부스택 입력한 값 안나오는 에러 수정

---

buildSrc/src/main/java/ProjectProperties.kt

🔀 :: (#349) - 버전코드, 버전이름 수정

---

buildSrc/src/main/java/ProjectProperties.kt

- version name 변경
- 1.1.0 -> 1.1.0-release

🔀 :: (#352) - version name 변경

---

presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageScreen.kt

🔀 :: (#356) - Change the award date picker on my page

---

data/src/main/java/com/msg/sms/data/remote/dto/student/response/GetStudentForStudentResponse.kt
presentation/src/main/java/com/sms/presentation/main/ui/detail/StudentDetailComponent.kt

포트폴리오 버튼을 선생님들만 들어갈 수 있도록 수정합니다.

🔀 :: (#361) - resolve error of out app on click portfolio button

---

presentation/src/main/java/com/sms/presentation/main/ui/fill_out_information/component/workcondition/WorkConditionComponent.kt

- 희망 연봉 인풋 필드 앱 크래시 이슈 해결
- 키보드 타입을 바꿔서 크래시 나지 않도록 수정

🔀 :: (#369) - 희망 연봉 인풋 필드 앱 크래시 이슈 해결

---

presentation/src/main/java/com/sms/presentation/main/ui/mypage/MyPageComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/life/SchoolScoreComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/work/WantPayComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/SchoolLifeSection.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/section/WorkConditionSection.kt

Change the keyboard type and create the not added feature on my page

🔀  :: (#366) - Create the feature of not added change my profile on my page

---

presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardNameComponent.kt
presentation/src/main/java/com/sms/presentation/main/ui/mypage/component/award/AwardTypeComponent.kt

🔀 ::(#379) - Change the place holder on my page

---

buildSrc/src/main/java/ProjectProperties.kt

- v1.1.2 업데이트를 위한 version code, version name 수정
- version code: 7 -> 8
- version name: 1.1.1 -> 1.1.2

🔀 :: (#385) - v1.1.2 업데이트를 위한 version code, version name 수정

---

design-system/src/main/java/com/msg/sms/design/component/SearchBar.kt

🔀 :: (#390) - Remove the not used code in search bar

---

app/build.gradle.kts
app/google-services.json
build.gradle.kts
buildSrc/src/main/java/Dependency.kt
buildSrc/src/main/java/Versions.kt
presentation/build.gradle.kts

- FireBase Clashlytics를 연동합니다.
- FireBase Clashlytics Gradle추가
- FireBase 대시보드

🔀 :: (#394) - FireBase Clashlytics를 연동합니다.

---

buildSrc/src/main/java/ProjectProperties.kt

- lottie 파일을 경량화 합니다.
- 경량화된 로티로 파일 변경
- version name, version code 업데이트

🔀 :: (#396) - lottie file 경량화

---

presentation/src/main/java/com/sms/presentation/main/ui/main/MainActivity.kt

- 스코프 함수를 통해 뷰모델 호출 부분의 가독성을 향상합니다.
- 기존 뷰모델이 중복으로 호출되던 부분을 run함수로 감싸 중복 코드를 줄이고 가독성을 향상합니다.
@JunJaBoy

🔀 :: (#402) - 스코프 함수를 통해 뷰모델 호출 부분 가독성 향상
